ToOrdr.web/Controllers/CustomersController.cs
// ***********************************************************************
// Assembly         : ToOrdr.web
// Author           : Manoj & Suraj
// Created          : 10-25-2018
//
// Last Modified By : Manoj
// Last Modified On : 04-17-2019
// ***********************************************************************
// <copyright file="CustomersController.cs" company="Microsoft">
//     Copyright © Microsoft 2017
// </copyright>
// <summary></summary>
// ***********************************************************************
using PagedList;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using ToOrdr.Core.Entities;
using ToOrdr.Core.Services.Interfaces;
using ToOrdr.Core.Util;
using ToOrdr.Localization;
using ToOrdr.Web.Models;
using ToOrdr.Web.ViewModels;

namespace ToOrdr.Web.Controllers
{
    /// <summary>
    /// Class CustomersController.
    /// Implements the <see cref="ToOrdr.Web.Controllers.BaseController" />
    /// </summary>
    /// <seealso cref="ToOrdr.Web.Controllers.BaseController" />
    public class CustomersController : BaseController
    {
        /// <summary>
        /// The customer service
        /// </summary>
        ICustomerService _customerService;
        /// <summary>
        /// The restaurant service
        /// </summary>
        IRestaurantService _restaurantService;
        /// <summary>
        /// The hotel service
        /// </summary>
        IHotelService _hotelService;


        /// <summary>
        /// Initializes a new instance of the <see cref="CustomersController"/> class.
        /// </summary>
        /// <param name="customerService">The customer service.</param>
        /// <param name="restaurantService">The restaurant service.</param>
        /// <param name="hotelService">The hotel service.</param>
        public CustomersController(ICustomerService customerService, IRestaurantService restaurantService, IHotelService hotelService)
        {
            _customerService = customerService;
            _restaurantService = restaurantService;
            _hotelService = hotelService;

        }


        /// <summary>
        /// Tests this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Test()
        {
            return View();
        }


        // GET: Customers
        /// <summary>
        /// Get All Customers.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Index()
        {
            var customers = _customerService.GetAllCustomers();
            return View(customers);
        }

        /// <summary>
        /// Creates Customer Sign In.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Create()
        {
            CustomerSignUpVM Customer = new CustomerSignUpVM();
            return View(Customer);
        }

        /// <summary>
        /// Creates the specified customer.
        /// </summary>
        /// <param name="customer">The customer.</param>
        /// <returns>ActionResult.</returns>
        [HttpPost]
        public ActionResult Create(CustomerSignUpVM customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Customer newCustomer = new Customer()
                    {
                        FirstName = customer.FirstName,
                        LastName = customer.LastName,
                        BirthDate = customer.DateOfBirth,
                        Email = customer.Email,
                        Password = customer.Password,
                        Telephone = customer.PhoneNumber,
                        City = customer.City,
                        Street = customer.Street,
                        Region = customer.Region,
                        CountryId = customer.CountryId,
                        Pincode = customer.Pincode
                    };

                    newCustomer.CreationDate = System.DateTime.Now;
                    newCustomer.ActiveStatus = false;

                    string activationCode = Guid.NewGuid().ToString();
                    newCustomer.ActivationCode = activationCode;

                    _customerService.CreateCustomer(newCustomer);
                    SendActivationEmail(newCustomer);

                    return RedirectToAction("AccountCreated", new { id = newCustomer.Id });
                }
                return View(customer);


            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(customer);
            }
        }

        /// <summary>
        /// Accounts the created.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult AccountCreated(int id)
        {
            var customer = _customerService.GetCustomerById(id);
            return View(customer);
        }

        /// <summary>
        /// Sends the activation email.
        /// </summary>
        /// <param name="customer">The customer.</param>
        private void SendActivationEmail(Customer customer)
        {
            try
            {
                //todo: make it asynchronnious call and template based

                using (System.Net.Mail.MailMessage mm = new System.Net.Mail.MailMessage("sender@gmail.com", customer.Email.ToString()))
                {

                    mm.Subject = "Account Activation";
                    string body = "Hello " + customer.FirstName.Trim() + ",";
                    body += "<br /><br />Please click the following link to activate your account";
                    body += "<br /><a href = '" + Request.Url.AbsoluteUri.Replace("Create", "Activated?ActivationCode=" + customer.ActivationCode + "&Id=" + customer.Id.ToString()) + "'>Click here to activate your account.</a>";
                    body += "<br /><br />Thanks";
                    mm.Body = body;
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential("donotreplycertigoa@gmail.com", "Certigoa2017#");
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                }


            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }


        }

        /// <summary>
        /// Activateds the specified activation code.
        /// </summary>
        /// <param name="ActivationCode">The activation code.</param>
        /// <param name="Id">The identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Activated(string ActivationCode, string Id)
        {
            var customer = _customerService.GetCustomerById(Convert.ToInt32(Id));
            if (customer.ActivationCode == ActivationCode)
            {
                customer.ActiveStatus = true;
                _customerService.ModifyCustomer(customer);
                ViewBag.Message = "Account Activated Successfully";
                return View();
            }
            else
            {
                ViewBag.Message = "Invalid  Activation Code";
                return View();
            }
        }

        /// <summary>
        /// Mies the account.
        /// </summary>
        /// <returns>ActionResult.</returns>
        [Authorize]
        public ActionResult MyAccount()
        {
            var customer = _customerService.GetAllCustomers(c => string.Equals(c.Email, User.Identity.Name, StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
            return View(customer);
        }

        // GET: Customer/Edit/5
        /// <summary>
        /// Edits Customer.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Edit()
        {
            ViewBag.Currencies = _customerService.GetAllCurrencies().Select(c => new { Id = c.Id, Code = c.Code + " - " + c.CurrencyName });
            ViewBag.Countries = _customerService.GetAllCountries().Select(c => new { Id = c.Id, Name = c.Name });

            ViewBag.GenderType = from GenderType e in Enum.GetValues(typeof(GenderType)) select new { Id = e.ToString(), Name = e.ToString() };
            var customer = GetAuthenticatedCustomer();
            return View(customer);
        }

        // POST: Customer/Edit/5

        /// <summary>
        /// Edits the specified customer.
        /// </summary>
        /// <param name="customer">The customer.</param>
        /// <returns>ActionResult.</returns>
        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            try
            {
                ViewBag.Currencies = _customerService.GetAllCurrencies().Select(c => new { Id = c.Id, Code = c.Code + " - " + c.CurrencyName });
                ViewBag.Countries = _customerService.GetAllCountries().Select(c => new { Id = c.Id, Name = c.Name });

                ViewBag.GenderType = from GenderType e in Enum.GetValues(typeof(GenderType)) select new { Id = e.ToString(), Name = e.ToString() };
                if (ModelState["Password"] != null) ModelState["Password"].Errors.Clear();

                if (ModelState.IsValid)
                {
                    var authenticatedCustomer = GetAuthenticatedCustomer();

                    authenticatedCustomer.FirstName = customer.FirstName;
                    authenticatedCustomer.LastName = customer.LastName;

ToOrdr.web/Views/Shared/_Footer.cshtml
<footer class="footer">
    <span class="pull-right">
        Example text
    </span>
    Company 2015-2020
</footer>

ToOrdr.web/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version" style="padding-top:5px">
    <a href="@Url.Content("~")">
        <img src="~/Content/Images/youordrLogo.png" height="55" />
    </a>

</div>
<nav role="navigation">
    <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
    <div class="small-logo">
        <span class="text-primary">HOMER APP</span>
    </div>
    <form role="search" class="navbar-form-custom" method="post" action="#">
        <div class="form-group">
            <input type="text" placeholder="Search something special" class="form-control" name="search">
        </div>
    </form>
    <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
            <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="" href="@Url.Action("Login", "CommonViews")">Login</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Register", "CommonViews")">Logout</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("ProfilePage", "AppViews")">Profile</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="navbar-right">
        <ul class="nav navbar-nav no-borders">
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-speaker"></i>
                </a>
                <ul class="dropdown-menu hdropdown notification animated flipInX">
                    <li>
                        <a>
                            <span class="label label-success">NEW</span> It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-warning">WAR</span> There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-danger">ERR</span> Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See all notifications</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-keypad"></i>
                </a>
                <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Projects", "AppViews")">
                                        <i class="pe pe-7s-portfolio text-info"></i>
                                        <h5>Projects</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Mailbox", "AppViews")">
                                        <i class="pe pe-7s-mail text-warning"></i>
                                        <h5>Email</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Contacts", "AppViews")">
                                        <i class="pe pe-7s-users text-success"></i>
                                        <h5>Contacts</h5>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Forum", "AppViews")">
                                        <i class="pe pe-7s-comment text-info"></i>
                                        <h5>Forum</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Index", "Analytics")">
                                        <i class="pe pe-7s-graph1 text-danger"></i>
                                        <h5>Analytics</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("FileManager", "AppViews")">
                                        <i class="pe pe-7s-box1 text-success"></i>
                                        <h5>Files</h5>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                    <i class="pe-7s-mail"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu hdropdown animated flipInX">
                    <div class="title">
                        You have 4 new messages
                    </div>
                    <li>
                        <a>
                            It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            Lorem Ipsum is simply dummy.
                        </a>
                    </li>
                    <li>
                        <a>
                            Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See All Messages</a></li>
                </ul>
            </li>
            <li>
                <a href="#" id="sidebar" class="right-sidebar-toggle">
                    <i class="pe-7s-upload pe-7s-news-paper"></i>
                </a>
            </li>
            <li class="dropdown">
                <a href="@Url.Action("signout","Account",new{area=""})">
                    <i class="pe-7s-upload pe-rotate-90"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

ToOrdr.web/Views/Shared/_Layout_Landing.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>youORDR | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="landing-page">

    <!-- Simple splash screen-->
    <div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    @*Navigation*@
    
    
    @*<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Content("~")">
                    <img src="~/Content/Images/youordrLogo.png" alt="2ORDR logo">
                </a>
            </div>
            <div id="navbar1" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
    </nav>*@


    
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Content("~")" class="navbar-brand" >
                    <img src="~/Content/Images/youordrLogo.png" height="55" />
                </a>
                <div class="brand-desc">
                    Some quote here
                </div>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                My Account
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Edit","Customers")">My Account</a></li>
                                <li><a href="@Url.Action("SignOut","Account")">Sign out</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Sign in", "SignIn", "Account", null, new { @class = "btn btn-default" })
                        </li>
                    }






                </ul>
            </div>
        </div>
    </nav>



    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

ToOrdr.web/Views/Shared/_NavigationCustomer.cshtml
<div id="navigation">
    @*<div class="profile-picture">
            <a href="@Url.Action("Index", "Dashboard")">
                <img src="~/Images/profile.jpg" class="img-circle m-b" alt="logo">
            </a>

            <div class="stats-label text-color">
                <span class="font-extra-bold font-uppercase">Robert Razer</span>

                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        <small class="text-muted">Founder of App <b class="caret"></b></small>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="analytics.html">Analytics</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div id="sparkline1" class="small-chart m-t-sm"></div>
                <div>
                    <h4 class="font-extra-bold m-b-xs">
                        $260 104,200
                    </h4>
                    <small class="text-muted">Your income from the last year in sales product X.</small>
                </div>
            </div>
        </div>*@

    <ul class="nav metismenu" id="side-menu">

        @if (Session["AllowBackend"] != null && Session["AllowBackend"].ToString() == "1")
        {
            if (Session["IsAdmin"] != null && Session["IsAdmin"].ToString() == "true")
            {
                @*<li class="@Html.IsSelected(controller: "Anything") bg-warning">
                    <a href="@Url.Action("Dashboard", "Admin", new { area = "admin" })"> <span class="nav-label">Backend Admin</span>  </a>
                </li>*@
            }
            else
            {
                @*<li class="@Html.IsSelected(controller: "Anything") bg-warning">
                    <a href="@Url.Action("SelectPremises", "Customers")"> <span class="nav-label">Backend Restaurant</span>  </a>
                </li>*@
            }
        }
        else
        {
            var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.GivenName);

                if (claim != null)
                {
                    <div class="profile-picture"><span>Hi</span> <strong>@claim.Value.ToString()</strong></div>
                }
            }
        }

        <li class="@Html.IsSelected(controller: "Customers")">
            <a href="#"><span class="nav-label">Activity</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "RecentOrders")"><a href="@Url.Action("RecentOrders", "Customers")">Recent Orders</a></li>
                <li class="@Html.IsSelected(action: "OrdersQueue")"><a href="@Url.Action("OrdersQueue", "Customers")">Orders Queue</a></li>
                <li class="@Html.IsSelected(action: "RecentRestaurants")"><a href="@Url.Action("RecentRestaurants", "Customers")">Recent Restaurants</a></li>
                 <li class="@Html.IsSelected(action: "RecentHotel")"><a href="@Url.Action("RecentHotels", "Customers")">Recent Hotels</a></li> 


                <li class="@Html.IsSelected(controller: "Customers")">
                    <a href="#"><span class="nav-label">All Reviews</span><span class="fa arrow"></span> </a>
                    <ul class="nav nav-third-level">
                        <li class="@Html.IsSelected(action: "RestaurantsReviews")"><a href="@Url.Action("RestaurantsReviews", "Customers")">Restaurants Reviews</a></li>
                        <li class="@Html.IsSelected(action: "HotelsReviews")"><a href="@Url.Action("HotelsReviews", "Customers")">Hotels Reviews</a></li>
                    </ul>
                </li>

                <li class="@Html.IsSelected(action: "RestaurantPreferences")"><a href="@Url.Action("RestaurantPreferences", "Customers")">Allergen Preferences</a></li>
                <li class="@Html.IsSelected(action: "IngredientPreferences") disabled"><a href="@Url.Action("IngredientPreferences", "Customers")">Ingredient Preferences</a></li>
                <li class="@Html.IsSelected(action: "FavoriteRestaurants")"><a href="@Url.Action("FavoriteRestaurants", "Customers")">Favorite Restaurants</a></li>
                <li class="@Html.IsSelected(action: "FavoriteHotels")"><a href="@Url.Action("FavoriteHotels", "Customers")">Favorite Hotels</a></li>

                <li class="@Html.IsSelected(action: "AccountDetails")"><a href="@Url.Action("Edit", "Customers")">Account Details</a></li>
                <li class="@Html.IsSelected(action: "ChangePassword")"><a href="@Url.Action("ChangePassword", "Customers")">Change Password</a></li>
                <li class="@Html.IsSelected(action: "PaymentCards")"><a href="@Url.Action("PaymentCards", "Customers")">Payment Cards</a></li>

                <li class="@Html.IsSelected(action: "CustomerFinancial") disabled"><a href="@Url.Action("CustomerFinancial", "Customers")">Financial</a></li>

            </ul>
        </li>

        @*<li class="@Html.IsSelected(controller: "Customers")">
            <a href="#"><span class="nav-label">Activity</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "RecentOrders")"><a href="@Url.Action("RecentOrders", "Customers")">Recent Orders</a></li>
                <li class="@Html.IsSelected(action: "RecentRestaurants")"><a href="@Url.Action("RecentRestaurants", "Customers")">Recent Restaurants</a></li>
                <li class="@Html.IsSelected(action: "RecentHotel")"><a href="@Url.Action("RecentHotels", "Customers")">Recent Hotels</a></li>
                <li class="@Html.IsSelected(action: "Reviews")"><a href="@Url.Action("Reviews", "Customers")">Reviews</a></li>

            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "Customers")">
            <a href="#"><span class="nav-label">My Account</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "AccountDetails")"><a href="@Url.Action("Edit", "Customers")">Account Details</a></li>
                <li class="@Html.IsSelected(action: "ChangePassword")"><a href="@Url.Action("ChangePassword", "Customers")">Change Password</a></li>
                <li class="@Html.IsSelected(action: "PaymentCards")"><a href="@Url.Action("PaymentCards", "Customers")">Payment Cards</a></li>
            </ul>
        </li>

        <li class="@Html.IsSelected(controller: "Customers")">
            <a href="#"><span class="nav-label">My Preferences</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "RestaurantPreferences")"><a href="@Url.Action("RestaurantPreferences", "Customers")">Restaurant Preferences</a></li>
                 <li class="@Html.IsSelected(action: "HotelPreferences")"><a href="@Url.Action("HotelPreferences", "Customers")">Hotel Preferences</a></li> 
                <li class="@Html.IsSelected(action: "FavoriteRestaurants")"><a href="@Url.Action("FavoriteRestaurants", "Customers")">Favorite Restaurants</a></li>
                <li class="@Html.IsSelected(action: "FavoriteHotels")"><a href="@Url.Action("FavoriteHotels", "Customers")">Favorite Hotels</a></li>
            </ul>
        </li>*@





    </ul>
</div>