ToOrdr.web/Areas/Admin/Controllers/AdminController.cs
// ***********************************************************************
// Assembly         : ToOrdr.web
// Author           : Manoj & Suraj
// Created          : 10-25-2018
//
// Last Modified By : Manoj
// Last Modified On : 04-17-2019
// ***********************************************************************
// <copyright file="AdminController.cs" company="Microsoft">
//     Copyright © Microsoft 2017
// </copyright>
// <summary></summary>
// ***********************************************************************
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using ToOrdr.Core.Entities;
using ToOrdr.Core.Helpers;
using ToOrdr.Core.Services.Interfaces;
using ToOrdr.Core.Util;
using ToOrdr.Localization;
using ToOrdr.Web.Controllers;
using ToOrdr.Web.ViewModels;

namespace ToOrdr.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Class AdminController.
    /// Implements the <see cref="ToOrdr.Web.Controllers.BaseController" />
    /// </summary>
    /// <seealso cref="ToOrdr.Web.Controllers.BaseController" />
    [Authorize(Roles = "Admin , ChainAdmin, RestaurantAdmin")]

    public class AdminController : BaseController
    {
        /// <summary>
        /// The API path
        /// </summary>
        string api_path = System.Configuration.ConfigurationManager.AppSettings["APIURL"];

        /// <summary>
        /// The restaurant service
        /// </summary>
        IRestaurantService _restaurantService;
        /// <summary>
        /// The customer service
        /// </summary>
        ICustomerService _customerService;
        /// <summary>
        /// The hotel service
        /// </summary>
        IHotelService _hotelService;
        /// <summary>
        /// The about youordr service
        /// </summary>
        IAboutYouOrdrService _aboutYouOrdrService;

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminController"/> class.
        /// </summary>
        /// <param name="restaurantService">The restaurant service.</param>
        /// <param name="customerService">The customer service.</param>
        /// <param name="hotelService">The hotel service.</param>
        /// <param name="aboutYouOrdrService">The about youordr service.</param>
        public AdminController(IRestaurantService restaurantService, ICustomerService customerService, IHotelService hotelService, IAboutYouOrdrService aboutYouOrdrService)
        {
            _restaurantService = restaurantService;
            _customerService = customerService;
            _hotelService = hotelService;
            _aboutYouOrdrService = aboutYouOrdrService;
        }
        // GET: Admin/Admin
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// Admin Dashboards.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Dashboard()
        {
            return View();
        }

        /// <summary>
        /// Orders the history.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult OrdersHistory()
        {
            return View();
        }

        /// <summary>
        /// Loads the orders history.
        /// </summary>
        /// <returns>Returns All Order History.</returns>
        [HttpPost]
        public ActionResult LoadOrdersHistory()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();

            //find search columns info
            var fromDate = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            var toDate = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
            var minAmount = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
            var maxAmount = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault();
            var restaurantId = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();
            var minAmt = minAmount == "" ? 0 : Convert.ToDouble(minAmount);
            var maxAmt = maxAmount == "" ? 0 : Convert.ToDouble(maxAmount);
            var restId = restaurantId == "" ? 0 : Convert.ToInt32(restaurantId);

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int Total = 0;

            var restOrderHistory = _restaurantService.GetRestaurantOrderHistory(fromDate, toDate, restId, minAmt, maxAmt, skip, pageSize, out Total);
            var data = restOrderHistory.Select(b => new
            {
                RestOrderId = b.Id,
                CustomerName = b.Customer.FirstName + " " + b.Customer.LastName,
                RestaurantName = b.Restaurant.Name,
                BookingDate = (b.ScheduledDate != null) ? b.ScheduledDate.ToString() : b.CreationDate.ToString(),
                Amount = b.OrderTotal,
                TableNumber = b.CustomerTableNumber != null ? b.RestaurantTable.TableNumber : 0,
                OrderStatus = ((Status_Type)b.OrderStatus).ToString(),
                PaymentStatus = b.PaymentStatus.ToString()
            });

            return Json(new { draw = draw, recordsFiltered = Total, recordsTotal = Total, data = data }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Restaurants recent orders.
        /// </summary>
        /// <returns>View all recent orders.</returns>
        public ActionResult RestaurantsRecentOrders()
        {
            return View();
        }

        /// <summary>
        /// Loads the restaurants recent orders.
        /// </summary>
        /// <returns>Load Restaurants Recent Orders.</returns>
        [HttpPost]
        public ActionResult LoadRestaurantsRecentOrders()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int Total = 0;
            var restId = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            int? selectedRestId;
            if (restId == "")
                selectedRestId = null;
            else
                selectedRestId = Convert.ToInt32(restId);
            var restRecentOrders = _restaurantService.GetRestRecentOrders(selectedRestId, skip, pageSize, out Total);
            var data = restRecentOrders.Select(b => new
            {
                RestOrderId = b.Id,
                CustomerName = b.Customer.FirstName + " " + b.Customer.LastName,
                RestaurantName = b.Restaurant.Name,
                BookingDate = b.ScheduledDate.ToString(),
                Amount = b.OrderTotal,
                TableNumber = b.CustomerTableNumber != null ? b.RestaurantTable.TableNumber : 0,
                OrderStatus = ((Status_Type)b.OrderStatus).ToString(),
                PaymentStatus = b.PaymentStatus.ToString()
            });

            return Json(new { draw = draw, recordsFiltered = Total, recordsTotal = Total, data = data }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Restaurants the automatic complete.
        /// </summary>
        /// <param name="prefix">The prefix should restaurant name keywords.</param>
        /// <returns>Restaurant AutoComplete.</returns>
        [HttpPost]
        public JsonResult RestaurantAutoComplete(string prefix)
        {
            var customer = GetAuthenticatedCustomer();
            var restaurants = _restaurantService.GetAllRestaurantsByName(customer.Id, prefix).Select(
                r => new
                {
                    Id = r.Id,
                    Name = r.Name
                });

            return Json(restaurants, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Hotels the automatic complete.
        /// </summary>
        /// <param name="prefix">The prefix.</param>
        /// <returns>JsonResult of Hotel AutoComplete.</returns>
        [HttpPost]
        public JsonResult HotelAutoComplete(string prefix)
        {
            var customer = GetAuthenticatedCustomer();
            var hotels = _hotelService.GetAllHotelsByName(customer.Id, prefix).Select(
                r => new
                {
                    Id = r.Id,
                    Name = r.Name
                });

            return Json(hotels, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Chains the automatic complete.
        /// </summary>
        /// <param name="prefix">The prefix.</param>
        /// <returns>JsonResult of Chain AutoComplete.</returns>
        public JsonResult ChainAutoComplete(string prefix)
        {
            var chains = _restaurantService.GetAllChainsByName(prefix).Select(c => new { Id = c.Id, Name = c.ChainName });
            return Json(chains, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Authorizeds users.
        /// </summary>
        /// <returns>List Authorized Users.</returns>
        public ActionResult AuthorizedUsers()
        {
            var customer = GetAuthenticatedCustomer();
            var authorizedUsers = _restaurantService.AuthorizedCustomers(customer.Id);
            return View(authorizedUsers);
        }

ToOrdr.web/Areas/Admin/Views/Admin/AddEditCuisine.cshtml
@model ToOrdr.Core.Entities.Cuisine
@using ToOrdr.Localization
@{
    ViewBag.Title = "AddEditCuisine";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section PageTitle{
    <h2 class="font-light m-b-xs">
        Cuisines
    </h2>
    <small>Add/Edit cuisine details</small>
}
<div class="hpanel">

    <div class="panel-body">

        @using (Html.BeginForm("SaveCuisine", "Admin", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data", id = "update_profile" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-lg-offset-2 col-md-5">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-1">
                        @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
                @{
            var api_path = System.Configuration.ConfigurationManager.AppSettings["APIURL"];
            var cuisineImg = ToOrdr.Core.Helpers.ImageHelper.GetPath(ToOrdr.Core.Helpers.ImagePathFor.Cuisines, Model.Image, Model.Id, api_path);
                }
                <div class="form-group row">
                    <label class="control-label control-label-left-align col-md-1 col-md-offset-1 text-left">Preview</label>
                    <div class="col-sm-1">
                        <img id="cuisine_img" class="image-preview-size" src="@Url.Content(cuisineImg)" onerror="this.onerror = null; this.src = '/Images/no_logo.png';" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    @Html.HiddenFor(model => model.Image)
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    <div class="col-sm-5">
                        <input type="file" name="uploadImage" id="uploadImage" class="form-control" onchange="showImage(this)" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancel", "ManageCuisines", "Admin", new { @class = "btn btn-primary", area = "Admin" })
                        <input type="submit" value="@Resources.Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@Scripts.Render("~/bundles/jqueryValidation")
<script>
    function showImage(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#cuisine_img').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }
</script>

ToOrdr.web/Areas/Admin/Views/Admin/AddMeasurementUnit.cshtml
@model ToOrdr.Core.Entities.MeasurementUnit
@{
    ViewBag.Title = "AddMeasurementUnit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Add Measurement Units
    </h2>
    <small>Add measurement units</small>
}
<div class="hpanel">

    <div class="panel-body">

        @using (Html.BeginForm("SaveMeasurementUnit", "Admin", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-lg-offset-2 col-md-5">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.UnitName, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Symbols, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Symbols, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Symbols, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" id="post_form_data" value="Save" class="btn btn-success" />
                        @Html.ActionLink("Cancel ", "ManageMeasurementUnit", "Admin",  new { area = "Admin", @class = "btn btn-primary btn-sm" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>

ToOrdr.web/Areas/Admin/Views/Admin/AddNutrition.cshtml
@model ToOrdr.Core.Entities.Nutrition
@{
    ViewBag.Title = "AddNutrition";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Add Nutrition
    </h2>
    <small>Add Nutrition</small>
}
<div class="hpanel">
    <div class="panel-body">

        @using (Html.BeginForm("SaveNutrition", "Admin", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-lg-offset-2 col-md-5">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeasurementUnitId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.DropDownListFor(model => model.MeasurementUnitId, new SelectList(ViewBag.MesurmentUnits, "Id", "UnitName"), "", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MeasurementUnitId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" id="post_form_data" value="Save" class="btn btn-success" />
                        @Html.ActionLink("Cancel ", "ManageNutrition", "Admin", new { area = "Admin", @class = "btn btn-primary btn-sm" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@Scripts.Render("~/bundles/jqueryValidation")

ToOrdr.web/Areas/Admin/Views/Admin/ManageDeletedCustomer.cshtml
@{
    ViewBag.Title = "ManageDeletedCustomer";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Deleted Customers
    </h2>
    <small>List of all deleted customers</small>
}
<div class="hpanel">
    <div class="panel-heading hbuilt">
        <div class="panel-tools">
            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        </div>
        Deleted Customers
    </div>
    <div class="panel-body">
        <table data-limit-navigation="5" id="manageDeletedCustomers" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Birth Date</th>
                    <th>Gender</th>
                    <th>City</th>
                    <th>Region</th>
                    <th>Pin Code</th>
                    <th>Telephone</th>
                    <th>Email</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#manageDeletedCustomers").DataTable({
            "searching": false,
            "ordering": false,
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": false, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "ajax": {
                "url": "/Admin/Admin/LoadAllDeletedCustomers/",
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                    { "data": "CustomerName", "name": "CustomerName", "autoWidth": true },
                    { "data": "BirthDate", "name": "BirthDate", "autoWidth": true },
                    { "data": "Gender", "name": "Gender", "autoWidth": true },
                    { "data": "City", "name": "City", "autoWidth": true },
                    { "data": "Region", "name": "Region", "autoWidth": true },
                    {"data": "Pinncode", "Pinncode": "Gender", "autoWidth": true},
                    { "data": "Telephone", "name": "Telephone", "autoWidth": true },
                    { "data": "Email", "Pinncode": "Email", "autoWidth": true }
            ]

        });
    });
</script>

ToOrdr.web/Areas/Admin/Views/Admin/ManageFoodProfiles.cshtml
@{
    ViewBag.Title = "ManageFoodProfiles";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Manage Food Profiles
    </h2>
    <small>List of food profiles</small>
}
<div class="hpanel">
    <div class="panel-heading hbuilt">
        <div class="panel-tools">
            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        </div>
        Manage Food Profiles
    </div>
    <div class="panel-body">
        @Html.ActionLink("Add", "AddFoodProfile", "Admin", new { area = "Admin" }, new { @class = "btn btn-success btn-sm new-btn-position" })<br />
        <table data-limit-navigation="5" id="food_profile" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>IsActive</th>
                    <th>Creation Date</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#food_profile").DataTable({
            "searching": false,
            "ordering": false,
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": false, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "ajax": {
                "url": "/Admin/Admin/LoadFoodProfiles",
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                    { "data": "Name", "name": "Name", "autoWidth": true },
                    { "data": "Description", "name": "Description", "autoWidth": true },
                    { "data": "IsActive", "name": "IsActive", "autoWidth": true },
                    { "data": "CreationDate", "name": "CreationDate", "autoWidth": true },
                    {
                        "data": "Image",
                        render: function (data) {
                            return '<img src="' + data + '"  width="100" height="55" />';
                        }
                    },
                    { "data": "FoodProfileId", "render": function (data, type, full) { return '<a class="fa fa-pencil-square-o fa-2x" title="Details" href="/Admin/Admin/EditFoodProfile/' + data + '"> </a> <a data-food-profile-id="' + data + '" class="js-delete fa fa-2x fa-trash"></a>' } }
            ]

        });

        $("#food_profile").on("click", ".js-delete", function () {
            var btn = $(this);
            swal({
                title: "Are you sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete!",
                cancelButtonText: "No, cancel!",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            url: "/Admin/Admin/DeleteFoodProfile/" + btn.attr("data-food-profile-id"),
                            method: "POST",
                            success: function (response) {
                                if (response.success) {
                                    btn.parents("tr").remove();
                                    swal("Deleted!", "Food profile has been deleted.", "success");
                                }
                                else {
                                    swal("Cancelled!", response.error, "warning");
                                }
                            },
                        });

                    } else {
                        swal("Cancelled", "Food profile is safe :)", "error");
                    }
                });
        });
    });
</script>

ToOrdr.web/Areas/Admin/Views/Admin/ManageIngredient.cshtml
@{
    ViewBag.Title = "ManageIngredient";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Ingredients
    </h2>
    <small>List of Ingredients</small>
}
<div class="hpanel">
    <div class="panel-heading hbuilt">
        <div class="panel-tools">
            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        </div>
        @Html.ActionLink(" ", "ManageIngredientCategories", "Admin", new { @class = "fa fa-2x fa-arrow-circle-left", area = "Admin" })
    </div>
    <div class="panel-body">
        @Html.ActionLink("Add", "AddIngredient", "Admin", new { area = "Admin", ingredientCatId = @ViewBag.IngredientCategoryId }, new { @class = "btn btn-success btn-sm new-btn-position" })<br />
        <table data-limit-navigation="5" id="ingredient" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
                <tr>
                    <th></th>
                    <th>Ingredient Group</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    function format(rowData) {
        var div = $('<div/>')
            .addClass('loading')
            .text('Loading...');

        $.ajax({
            url: '/Admin/Admin/LoadIngredientFoodProfiles',
            data: {
                IngredientId: rowData.IngredientId
            },
            success: function (response) {
                div
                    .html(response)
                    .removeClass('loading');
            },
            error: function () {
                alert("Oops!....");
            }
        });

        return div;
    }
    $(document).ready(function () {
        var table = $("#ingredient").DataTable({
            "searching": false,
            "ordering": false,
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": false, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "dom": '<"top"i>rt<"bottom"lp><"clear">',
            "ajax": {
                "url": "/Admin/Admin/LoadIngredients?ingredientCatId=@ViewBag.IngredientCategoryId",
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                     {
                         className: 'details-control',
                         orderable: false,
                         data: null,
                         defaultContent: ''
                     },
                    { "data": "IngredientCategory", "name": "IngredientCategory", "autoWidth": true },
                    { "data": "Name", "name": "Name", "autoWidth": true },
                    { "data": "Description", "name": "Description", "autoWidth": true },
                     {
                         "data": "Image",
                         render: function (data) {
                             return '<img src="' + data + '"  width="100" height="55" />';
                         }
                     },
                    { "data": "IngredientId", "render": function (data, type, full) { return '<a class="fa fa-pencil-square-o fa-2x" title="Details" href="/Admin/Admin/EditIngredient/' + data + '"> </a> <a data-ingredient-id="' + data + '" class="js-delete fa fa-2x fa-trash"></a> <a class="fa fa-2x fa-list-alt" title="Nutrition values" href="/Admin/Admin/ManageIngredientNutritionValues/' + data + '"></a>' } }
            ]

        });

        // Add event listener for opening and closing details
        $('#ingredient').on('click', 'td.details-control', function () {
            var tr = $(this).closest('tr');
            var row = table.row(tr);

            if (row.child.isShown()) {
                // This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
            }
            else {
                // Open this row
                row.child(format(row.data())).show();
                tr.addClass('shown');
            }
        });




        $("#ingredient").on("click", ".js-delete", function () {
            var btn = $(this);
            swal({
                title: "Are you sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete!",
                cancelButtonText: "No, cancel!",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            url: "/Admin/Admin/DeleteIngredient/" + btn.attr("data-ingredient-id"),
                            method: "POST",
                            success: function (response) {
                                if (response.status) {
                                    btn.parents("tr").remove();
                                    swal("Deleted!", "Ingredient has been deleted.", "success");
                                }
                                else {
                                    swal("Cancelled!", response.error, "warning");
                                }
                            },
                        });

                    } else {
                        swal("Cancelled", "Ingredient is safe :)", "error");
                    }
                });
        });
    });
</script>