ToOrdr.web/Areas/Admin/Controllers/HotelExcursionController.cs
// ***********************************************************************
// Assembly         : ToOrdr.web
// Author           : Manoj & Suraj
// Created          : 10-25-2018
//
// Last Modified By : Manoj
// Last Modified On : 05-07-2019
// ***********************************************************************
// <copyright file="HotelExcursionController.cs" company="Microsoft">
//     Copyright © Microsoft 2017
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrdr.Core.Entities;
using ToOrdr.Core.Helpers;
using ToOrdr.Core.Services.Interfaces;
using ToOrdr.Localization;
using ToOrdr.Web.Controllers;

namespace ToOrdr.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Class HotelExcursionController.
    /// Implements the <see cref="ToOrdr.Web.Controllers.BaseController" />
    /// </summary>
    /// <seealso cref="ToOrdr.Web.Controllers.BaseController" />
    public class HotelExcursionController : BaseController
    {
        /// <summary>
        /// The hotel service
        /// </summary>
        IHotelService _hotelService;
        /// <summary>
        /// The payment service
        /// </summary>
        IPaymentService _paymentService;
        /// <summary>
        /// Initializes a new instance of the <see cref="HotelExcursionController"/> class.
        /// </summary>
        /// <param name="hotelService">The hotel service.</param>
        /// <param name="paymentService">The payment service.</param>
        public HotelExcursionController(IHotelService hotelService, IPaymentService paymentService)
        {
            _hotelService = hotelService;
            _paymentService = paymentService;
        }
        // GET: Admin/HotelExcursion
        /// <summary>
        /// Manages the excursion.
        /// </summary>
        /// <returns>ActionResult Manage Excursion.</returns>
        public ActionResult ManageExcursion()
        {
            return View();
        }
        /// <summary>
        /// Loads the excursion.
        /// </summary>
        /// <returns>ActionResult Load Excursion.</returns>
        [HttpPost]
        public ActionResult LoadExcursion()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int Total = 0;

            var excursions = _hotelService.GetExcursions(skip, pageSize, out Total);
            var api_path = System.Configuration.ConfigurationManager.AppSettings["APIURL"];

            var data = excursions.Select(b => new
            {
                ExcursionId = b.Id,
                ExcursionName = b.Name,
                ExcursionDescription = b.Description,
                IsActive = b.IsActive
            });

            return Json(new { draw = draw, recordsFiltered = Total, recordsTotal = Total, data = data }, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// Adds the excursion.
        /// </summary>
        /// <returns>ActionResult Add Excursion.</returns>
        public ActionResult AddExcursion()
        {
            Excursion hotelExcursion = new Excursion();
            return View("AddEditExcursion", hotelExcursion);
        }

        /// <summary>
        /// Saves the excursion.
        /// </summary>
        /// <param name="excursion">The excursion.</param>
        /// <param name="uploadFile">The upload file.</param>
        /// <returns>ActionResult Save new created Excursion.</returns>
        public ActionResult SaveExcursion(Excursion excursion, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (excursion.Id == 0)
                    {

                        var excursionResult = _hotelService.CreateExcursion(excursion);
                        return RedirectToAction("ManageExcursion");
                    }
                    else
                    {
                        var res = _hotelService.ModifyExcursion(excursion);
                        return RedirectToAction("ManageExcursion");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Validation Error");
                    return View("AddEditExcursion", excursion);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View("AddEditExcursion", excursion);
            }
        }

        /// <summary>
        /// Edits the excursion.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult Edit Excursion.</returns>
        public ActionResult EditExcursion(int id)
        {
            var escursionService = _hotelService.GetExcursionById(id);
            return View("AddEditExcursion", escursionService);
        }

        /// <summary>
        /// Deletes the excursion.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult Delete Excursion.</returns>
        [HttpPost]
        public ActionResult DeleteExcursion(int id)
        {
            try
            {
                _hotelService.DeleteExcursion(id);
                return Json(new { status = true });
            }
            catch
            {
                return Json(new { status = false, error = "This excursion service cannot be deleted, bacause it is already in use" });
            }
        }


        /// <summary>
        /// Manages the hotel excursion.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult Manage HotelExcursion.</returns>
        public ActionResult ManageHotelExcursion(int id)
        {
            ViewBag.HotelServiceId = id;
            return View();
        }

        /// <summary>
        /// Loads the hotel excursion.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>ActionResult Load HotelExcursion.</returns>
        [HttpPost]
        public ActionResult LoadHotelExcursion(int id)
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int Total = 0;
            var hotelExcursion = _hotelService.GetAllHotelExcursions(id, skip, pageSize, out Total);
            var data = hotelExcursion.Select(b => new
            {
                HotelExcursionId = b.Id,
                HotelServiceName = b.HotelServices.Services.ServiceName,
                ExcursionName = b.Excursion.Name,
                IsActive = b.IsActive
            });

            return Json(new { draw = draw, recordsFiltered = Total, recordsTotal = Total, data = data }, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// Adds the hotel excursion.
        /// </summary>
        /// <param name="HotelServiceId">The hotel service identifier.</param>
        /// <returns>ActionResult Add HotelExcursion.</returns>
        public ActionResult AddHotelExcursion(int HotelServiceId)
        {
            HotelExcursion hotelExcursion = new HotelExcursion();
            hotelExcursion.HotelServiceId = HotelServiceId;
            var unassignExcursion = _hotelService.GetUnassignExcursion(HotelServiceId).Select(
                 r => new
                 {
                     ExcursionId = r.Id,
                     Name = r.Name
                 }).ToList();
            ViewBag.Excursions = new MultiSelectList(unassignExcursion, "ExcursionId", "Name");
            return View(hotelExcursion);
        }


        /// <summary>
        /// Saves the hotel excursion.
        /// </summary>
        /// <param name="hotelExcursion">The hotel excursion.</param>
        /// <returns>ActionResult Save HotelExcursion.</returns>
        [HttpPost]
        public ActionResult SaveHotelExcursion(HotelExcursion hotelExcursion)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<HotelExcursion> listHotelExcursion = new List<HotelExcursion>();

                    var ExcursionIds = Request.Form["ExcursionId"];

                    if (ExcursionIds != null)
                    {
                        string[] listExcursionIds = ExcursionIds.Split(',');
                        foreach (var eachExcId in listExcursionIds)
                        {
                            HotelExcursion eachHotelExcursion = new HotelExcursion()
                            {
                                HotelServiceId = hotelExcursion.HotelServiceId,
                                ExcursionId = Convert.ToInt32(eachExcId)
                            };
                            listHotelExcursion.Add(eachHotelExcursion);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Please select excursions to be added");
                        var unassignExcursion = _hotelService.GetUnassignExcursion(hotelExcursion.HotelServiceId).Select(
                                                  r => new

ToOrdr.web/Areas/Admin/Views/HotelExcursion/AddEditExcursion.cshtml
@model ToOrdr.Core.Entities.Excursion
@{
    ViewBag.Title = "AddEditExcursion";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHotel.cshtml";
}
@section PageTitle{
    <h2 class="font-light m-b-xs">
        Excursion
    </h2>
    <small>Add/Edit excursion</small>
}

<div class="hpanel">
    <div class="panel-heading hbuilt">
        <div class="panel-tools">
            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        </div>
        Excursion
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("SaveExcursion", "HotelExcursion", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-5">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-5">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-5">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-1">
                        @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)
                <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2">
                        <button type="button" id="hotel_excursion" class="btn btn-primary">Cancel</button>
                        <input type="submit" class="btn btn-success" value="Save" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jquery/js")
<script>
    $(document).ready(function () {
        $("#hotel_excursion").on("click", function () {
            window.location.href = '/Admin/HotelExcursion/ManageExcursion' ;
        });
    });

    function show(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#excursion_img').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }
</script>

ToOrdr.web/Areas/Admin/Views/HotelExcursion/AddEditExcursionIngredient.cshtml
@model ToOrdr.Core.Entities.ExcursionIngredient
@using ToOrdr.Localization;
@{
    ViewBag.Title = "AddEditExcursionIngredient";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHotel.cshtml";
}
@section PageTitle{
    <h2 class="font-light m-b-xs">
        Excursion Ingredient Details
    </h2>
    <small>Add/Edit Excursion Ingredient details</small>
}
<div class="hpanel">
    <div class="panel-body">

        @using (Html.BeginForm("SaveExcursionIngredient", "HotelExcursion", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-2">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.ExcursionIngredientCategoryId)
                <div class="section-title">
                    <span class="glyphicon glyphicon-cutlery"></span><span class="glyphicon-text-space"><label>Ingredient Details</label></span>
                </div><hr class="hr-top-margin" />

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>


                @{
            var api_path = System.Configuration.ConfigurationManager.AppSettings["APIURL"];
            var excIngredientImage = ToOrdr.Core.Helpers.ImageHelper.GetPath(ToOrdr.Core.Helpers.ImagePathFor.ExcursionIngredient, Model.IngredientImage, Model.Id, api_path);
                }
                <div class="form-group row">
                    <label class="control-label control-label-left-align col-md-1 col-md-offset-1 text-left">Preview</label>
                    <div class="col-sm-1">
                        <img id="excIngredient_img" class="image-preview-size" src="@Url.Content(excIngredientImage)" onerror="this.onerror = null; this.src = '/Images/no_logo.png';" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IngredientImage, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    @Html.HiddenFor(model => model.IngredientImage)
                    @Html.ValidationMessageFor(model => model.IngredientImage, "", new { @class = "text-danger" })
                    <div class="col-sm-5">
                        <input type="file" name="uploadExcIngredientImage" id="uploadExcIngredientImage" class="form-control" onchange="showImage(this)" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancel", "ManageExcursionIngredients", "HotelExcursion", new { excIngredientCatId = Model.ExcursionIngredientCategoryId }, new { @class = "btn btn-primary", area = "Admin" })
                        <input type="submit" value="@Resources.Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

@Scripts.Render("~/bundles/jqueryValidation")
<script>

    function showImage(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#excIngredient_img').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }
</script>

ToOrdr.web/Areas/Admin/Views/HotelExcursion/AddEditExcursionIngredientCategory.cshtml
@model ToOrdr.Core.Entities.ExcursionIngredientCategory
@using ToOrdr.Localization
@{
    ViewBag.Title = "AddEditExcursionIngredientCategory";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHotel.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Excursion Ingredient Category
    </h2>
    <small>Add/Edit excursion ingredient category</small>
}
<div class="hpanel">

    <div class="panel-body">

        @using (Html.BeginForm("SaveExcursionIngredientCategory", "HotelExcursion", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-lg-offset-2 col-md-5">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreationDate)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-1">
                        @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
                @{
            var api_path = System.Configuration.ConfigurationManager.AppSettings["APIURL"];
            var excIngredientCatImg = ToOrdr.Core.Helpers.ImageHelper.GetPath(ToOrdr.Core.Helpers.ImagePathFor.ExcursionIngredientCategories, Model.Image, Model.Id, api_path);
                }
                <div class="form-group row">
                    <label class="control-label control-label-left-align col-md-1 col-md-offset-1 text-left">Preview</label>
                    <div class="col-sm-1">
                        <img id="excIngredientCat_img" class="image-preview-size" src="@Url.Content(excIngredientCatImg)" onerror="this.onerror = null; this.src = '/Images/no_logo.png';" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label control-label-left-align col-md-1 col-md-offset-1" })
                    @Html.HiddenFor(model => model.Image)
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    <div class="col-sm-5">
                        <input type="file" name="uploadImage" id="uploadImage" class="form-control" onchange="showImage(this)" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancel", "ManageExcursionIngredientCategories", "HotelExcursion", new { @class = "btn btn-primary", area = "Admin" })
                        <input type="submit" value="@Resources.Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@Scripts.Render("~/bundles/jqueryValidation")
<script>
    function showImage(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#excIngredientCat_img').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }
</script>

ToOrdr.web/Areas/Admin/Views/HotelExcursion/AddExcursionDetailIngredient.cshtml
@model ToOrdr.Core.Entities.ExcursionDetailIngredient
@{
    ViewBag.Title = "AddExcursionDetailIngredient";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHotel.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Excursion Detail Ingredient
    </h2>
    <small>Add multiple excursion detail ingredient at once</small>
}
<div class="hpanel">
    <div class="panel-body">

        @using (Html.BeginForm("SaveExcursionDetailIngredient", "HotelExcursion", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-2">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.ExcursionDetailsId)
                <div class="form-group">
                    @Html.Label("Excursion Ingredients", htmlAttributes: new { @class = "control-label  col-md-2 " })
                    <div class="col-md-5">
                        @Html.DropDownList("ExcIngredientId", (MultiSelectList)ViewBag.ExcursionIngredients, new { @class = "form-control", @multiple = "multiple" })
                        @Html.ValidationMessage("ExcIngredientId", "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Save" class="btn btn-success" />
                        @Html.ActionLink("Cancel", "ManageExcursionDetailIngredients", "HotelExcursion", new { area = "Admin", id = Model.ExcursionDetailsId }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>

ToOrdr.web/Areas/Admin/Views/HotelExcursion/AddHotelExcursion.cshtml
@model ToOrdr.Core.Entities.HotelExcursion
@{
    ViewBag.Title = "AddHotelExcursion";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHotel.cshtml";
}

@section PageTitle{
    <h2 class="font-light m-b-xs">
        Hotel Excursion
    </h2>
    <small>Add hotel excursion</small>
}
<div class="hpanel">
    <div class="panel-body">

        @using (Html.BeginForm("SaveHotelExcursion", "HotelExcursion", new { area = "Admin" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-2">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.HotelServiceId)
                <div class="form-group">
                    @Html.Label("Excursion", htmlAttributes: new { @class = "control-label  col-md-2 " })
                    <div class="col-md-5">
                        @Html.DropDownList("ExcursionId", (MultiSelectList)ViewBag.Excursions, new { @class = "form-control", @multiple = "multiple" })
                        @Html.ValidationMessage("ExcursionId", "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-1">
                        @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Save" class="btn btn-success" />
                        @Html.ActionLink("Cancel", "ManageHotelExcursion", "HotelExcursion", new { area = "Admin", id = Model.HotelServiceId }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>

ToOrdr.web/Areas/Admin/Views/HotelExcursion/ManageExcursion.cshtml
@{
    ViewBag.Title = "ManageExcursion";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutHotel.cshtml";
}
@section PageTitle{
    <h2 class="font-light m-b-xs">
        Excursions
    </h2>
    <small>List of hotel excursions</small>
}
<div class="hpanel">
    <div class="panel-heading hbuilt">
        <div class="panel-tools">
            <a class="showhide"><i class="fa fa-chevron-up"></i></a>
        </div>
        Excursions
    </div>
    <div class="panel-body">
        @Html.ActionLink("Add", "AddExcursion", "HotelExcursion", new { area = "Admin" }, new { @class = "btn btn-success btn-sm new-btn-position" })<br />
        <table data-limit-navigation="5" id="manageExcursions" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>IsActive</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#manageExcursions").DataTable({
            "searching": false,
            "ordering": false,
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": false, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "ajax": {
                "url": "/Admin/HotelExcursion/LoadExcursion",
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                    { "data": "ExcursionName", "name": "ExcursionName", "autoWidth": true },
                    { "data": "ExcursionDescription", "name": "ExcursionDescription", "autoWidth": true },
                    { "data": "IsActive", "name": "IsActive", "autoWidth": true },
                    { "data": "ExcursionId", "render": function (data, type, full) { return '<a class="fa fa-pencil-square-o fa-2x" title="Details" href="/Admin/HotelExcursion/EditExcursion/' + data + '"> </a> <a data-excursion-id="' + data + '" class="js-delete fa fa-2x fa-trash"></a>' } }

            ]

        });

        $("#manageExcursions").on("click", ".js-delete", function () {
        var btn = $(this);
        swal({
            title: "Are you sure?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete!",
            cancelButtonText: "No, cancel!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        url: "/Admin/HotelExcursion/DeleteExcursion/" + btn.attr("data-excursion-id"),
                        method: "POST",
                        success: function (response) {
                            if (response.status) {
                                btn.parents("tr").remove();
                                swal("Deleted!", "Excursion has been deleted.", "success");
                            }
                            else {
                                swal("Cancelled!", response.error, "warning");
                            }
                        },
                    });

                } else {
                    swal("Cancelled", "Excursion is safe :)", "error");
                }
            });
    });
    });
</script>